# Model files
VIDEO_DETECTION_MODEL = "yolo26m.pt"
POSTURE_ESTIMATION_MODEL = "yolo26m-pose.pt"

# Inference Thresholds
CONFIDENCE_THRESHOLD = 0.25
IOU_THRESHOLD = 0.7

# Posture Logic Thresholds
KNEE_STRAIGHT = 160
KNEE_BENT = 120
HIP_STRAIGHT = 160
HIP_BENT = 130
VERTICAL_DIST_SITTING = 40
